#!/bin/bash
# SSH into the server and apply the fix

echo "This script will SSH into your server and:"
echo "1. Clear bun's cache"
echo "2. Restart the service properly"
echo "3. Apply the database schema fix"
echo ""
echo "You'll need to run this manually with your SSH credentials:"
echo ""
echo "ssh YOUR_USER@YOUR_HOST << 'ENDSSH'"
echo "cd /opt/gigz-api"
echo ""
echo "# Clear bun cache to force recompilation"
echo "rm -rf node_modules/.cache"
echo "rm -rf ~/.bun/install/cache"
echo ""
echo "# Restart service"
echo "sudo systemctl stop gigz-api"
echo "sudo systemctl start gigz-api"
echo ""
echo "# Wait for service to start"
echo "sleep 5"
echo ""
echo "# Apply the database schema fix"
echo "psql \$DATABASE_URL << 'SQL'"
echo "UPDATE \"_SCHEMA\""
echo "SET schema = jsonb_set("
echo "    schema,"
echo "    '{fields,user,required}',"
echo "    'false',"
echo "    true"
echo ")"
echo "WHERE \"className\" = 'UserConcert';"
echo "SQL"
echo ""
echo "# Verify the fix"
echo "curl -f http://localhost:3000/health && echo 'Service is healthy'"
echo "ENDSSH"
